// <auto-generated />
using Customer.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Customer.Persistence.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Customer")
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Customer.Domain.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ClientId");

                    b.HasIndex("ClientId");

                    b.ToTable("Clients", "Customer");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            Name = "Cliente 1"
                        },
                        new
                        {
                            ClientId = 2,
                            Name = "Cliente 2"
                        },
                        new
                        {
                            ClientId = 3,
                            Name = "Cliente 3"
                        },
                        new
                        {
                            ClientId = 4,
                            Name = "Cliente 4"
                        },
                        new
                        {
                            ClientId = 5,
                            Name = "Cliente 5"
                        },
                        new
                        {
                            ClientId = 6,
                            Name = "Cliente 6"
                        },
                        new
                        {
                            ClientId = 7,
                            Name = "Cliente 7"
                        },
                        new
                        {
                            ClientId = 8,
                            Name = "Cliente 8"
                        },
                        new
                        {
                            ClientId = 9,
                            Name = "Cliente 9"
                        },
                        new
                        {
                            ClientId = 10,
                            Name = "Cliente 10"
                        },
                        new
                        {
                            ClientId = 11,
                            Name = "Cliente 11"
                        },
                        new
                        {
                            ClientId = 12,
                            Name = "Cliente 12"
                        },
                        new
                        {
                            ClientId = 13,
                            Name = "Cliente 13"
                        },
                        new
                        {
                            ClientId = 14,
                            Name = "Cliente 14"
                        },
                        new
                        {
                            ClientId = 15,
                            Name = "Cliente 15"
                        },
                        new
                        {
                            ClientId = 16,
                            Name = "Cliente 16"
                        },
                        new
                        {
                            ClientId = 17,
                            Name = "Cliente 17"
                        },
                        new
                        {
                            ClientId = 18,
                            Name = "Cliente 18"
                        },
                        new
                        {
                            ClientId = 19,
                            Name = "Cliente 19"
                        },
                        new
                        {
                            ClientId = 20,
                            Name = "Cliente 20"
                        },
                        new
                        {
                            ClientId = 21,
                            Name = "Cliente 21"
                        },
                        new
                        {
                            ClientId = 22,
                            Name = "Cliente 22"
                        },
                        new
                        {
                            ClientId = 23,
                            Name = "Cliente 23"
                        },
                        new
                        {
                            ClientId = 24,
                            Name = "Cliente 24"
                        },
                        new
                        {
                            ClientId = 25,
                            Name = "Cliente 25"
                        },
                        new
                        {
                            ClientId = 26,
                            Name = "Cliente 26"
                        },
                        new
                        {
                            ClientId = 27,
                            Name = "Cliente 27"
                        },
                        new
                        {
                            ClientId = 28,
                            Name = "Cliente 28"
                        },
                        new
                        {
                            ClientId = 29,
                            Name = "Cliente 29"
                        },
                        new
                        {
                            ClientId = 30,
                            Name = "Cliente 30"
                        },
                        new
                        {
                            ClientId = 31,
                            Name = "Cliente 31"
                        },
                        new
                        {
                            ClientId = 32,
                            Name = "Cliente 32"
                        },
                        new
                        {
                            ClientId = 33,
                            Name = "Cliente 33"
                        },
                        new
                        {
                            ClientId = 34,
                            Name = "Cliente 34"
                        },
                        new
                        {
                            ClientId = 35,
                            Name = "Cliente 35"
                        },
                        new
                        {
                            ClientId = 36,
                            Name = "Cliente 36"
                        },
                        new
                        {
                            ClientId = 37,
                            Name = "Cliente 37"
                        },
                        new
                        {
                            ClientId = 38,
                            Name = "Cliente 38"
                        },
                        new
                        {
                            ClientId = 39,
                            Name = "Cliente 39"
                        },
                        new
                        {
                            ClientId = 40,
                            Name = "Cliente 40"
                        },
                        new
                        {
                            ClientId = 41,
                            Name = "Cliente 41"
                        },
                        new
                        {
                            ClientId = 42,
                            Name = "Cliente 42"
                        },
                        new
                        {
                            ClientId = 43,
                            Name = "Cliente 43"
                        },
                        new
                        {
                            ClientId = 44,
                            Name = "Cliente 44"
                        },
                        new
                        {
                            ClientId = 45,
                            Name = "Cliente 45"
                        },
                        new
                        {
                            ClientId = 46,
                            Name = "Cliente 46"
                        },
                        new
                        {
                            ClientId = 47,
                            Name = "Cliente 47"
                        },
                        new
                        {
                            ClientId = 48,
                            Name = "Cliente 48"
                        },
                        new
                        {
                            ClientId = 49,
                            Name = "Cliente 49"
                        },
                        new
                        {
                            ClientId = 50,
                            Name = "Cliente 50"
                        },
                        new
                        {
                            ClientId = 51,
                            Name = "Cliente 51"
                        },
                        new
                        {
                            ClientId = 52,
                            Name = "Cliente 52"
                        },
                        new
                        {
                            ClientId = 53,
                            Name = "Cliente 53"
                        },
                        new
                        {
                            ClientId = 54,
                            Name = "Cliente 54"
                        },
                        new
                        {
                            ClientId = 55,
                            Name = "Cliente 55"
                        },
                        new
                        {
                            ClientId = 56,
                            Name = "Cliente 56"
                        },
                        new
                        {
                            ClientId = 57,
                            Name = "Cliente 57"
                        },
                        new
                        {
                            ClientId = 58,
                            Name = "Cliente 58"
                        },
                        new
                        {
                            ClientId = 59,
                            Name = "Cliente 59"
                        },
                        new
                        {
                            ClientId = 60,
                            Name = "Cliente 60"
                        },
                        new
                        {
                            ClientId = 61,
                            Name = "Cliente 61"
                        },
                        new
                        {
                            ClientId = 62,
                            Name = "Cliente 62"
                        },
                        new
                        {
                            ClientId = 63,
                            Name = "Cliente 63"
                        },
                        new
                        {
                            ClientId = 64,
                            Name = "Cliente 64"
                        },
                        new
                        {
                            ClientId = 65,
                            Name = "Cliente 65"
                        },
                        new
                        {
                            ClientId = 66,
                            Name = "Cliente 66"
                        },
                        new
                        {
                            ClientId = 67,
                            Name = "Cliente 67"
                        },
                        new
                        {
                            ClientId = 68,
                            Name = "Cliente 68"
                        },
                        new
                        {
                            ClientId = 69,
                            Name = "Cliente 69"
                        },
                        new
                        {
                            ClientId = 70,
                            Name = "Cliente 70"
                        },
                        new
                        {
                            ClientId = 71,
                            Name = "Cliente 71"
                        },
                        new
                        {
                            ClientId = 72,
                            Name = "Cliente 72"
                        },
                        new
                        {
                            ClientId = 73,
                            Name = "Cliente 73"
                        },
                        new
                        {
                            ClientId = 74,
                            Name = "Cliente 74"
                        },
                        new
                        {
                            ClientId = 75,
                            Name = "Cliente 75"
                        },
                        new
                        {
                            ClientId = 76,
                            Name = "Cliente 76"
                        },
                        new
                        {
                            ClientId = 77,
                            Name = "Cliente 77"
                        },
                        new
                        {
                            ClientId = 78,
                            Name = "Cliente 78"
                        },
                        new
                        {
                            ClientId = 79,
                            Name = "Cliente 79"
                        },
                        new
                        {
                            ClientId = 80,
                            Name = "Cliente 80"
                        },
                        new
                        {
                            ClientId = 81,
                            Name = "Cliente 81"
                        },
                        new
                        {
                            ClientId = 82,
                            Name = "Cliente 82"
                        },
                        new
                        {
                            ClientId = 83,
                            Name = "Cliente 83"
                        },
                        new
                        {
                            ClientId = 84,
                            Name = "Cliente 84"
                        },
                        new
                        {
                            ClientId = 85,
                            Name = "Cliente 85"
                        },
                        new
                        {
                            ClientId = 86,
                            Name = "Cliente 86"
                        },
                        new
                        {
                            ClientId = 87,
                            Name = "Cliente 87"
                        },
                        new
                        {
                            ClientId = 88,
                            Name = "Cliente 88"
                        },
                        new
                        {
                            ClientId = 89,
                            Name = "Cliente 89"
                        },
                        new
                        {
                            ClientId = 90,
                            Name = "Cliente 90"
                        },
                        new
                        {
                            ClientId = 91,
                            Name = "Cliente 91"
                        },
                        new
                        {
                            ClientId = 92,
                            Name = "Cliente 92"
                        },
                        new
                        {
                            ClientId = 93,
                            Name = "Cliente 93"
                        },
                        new
                        {
                            ClientId = 94,
                            Name = "Cliente 94"
                        },
                        new
                        {
                            ClientId = 95,
                            Name = "Cliente 95"
                        },
                        new
                        {
                            ClientId = 96,
                            Name = "Cliente 96"
                        },
                        new
                        {
                            ClientId = 97,
                            Name = "Cliente 97"
                        },
                        new
                        {
                            ClientId = 98,
                            Name = "Cliente 98"
                        },
                        new
                        {
                            ClientId = 99,
                            Name = "Cliente 99"
                        },
                        new
                        {
                            ClientId = 100,
                            Name = "Cliente 100"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
