trigger:
- master #git branch

pool:
  vmImage: 'windows-2022'

variables:
  buildConfiguration: 'Release'
  proyecto: 'src/Clients/Client.WebClient/Client.WebClient.csproj'

steps:
- task: CmdLine@2
  displayName: 'dotnet build $(buildConfiguration)'
  inputs:
    script: 'dotnet build --configuration $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: 'Publishing App'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: $(proyecto)
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory) --runtime win-x86 --no-self-contained' #la arquitectura x86 es la del server de azure, si fuese una version preview de net core sería --self-contained
    zipAfterPublish: false
    modifyOutputPath: false
- task: PublishBuildArtifacts@1
  displayName: 'Publishing artifacts on the directory'