// <auto-generated />
using Catalog.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Catalog.Persistence.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Catalog")
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("Products", "Catalog");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "descripcion 1",
                            Name = "nombre 1",
                            Price = 174m
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "descripcion 2",
                            Name = "nombre 2",
                            Price = 186m
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "descripcion 3",
                            Name = "nombre 3",
                            Price = 44m
                        },
                        new
                        {
                            ProductId = 4,
                            Description = "descripcion 4",
                            Name = "nombre 4",
                            Price = 148m
                        },
                        new
                        {
                            ProductId = 5,
                            Description = "descripcion 5",
                            Name = "nombre 5",
                            Price = 235m
                        },
                        new
                        {
                            ProductId = 6,
                            Description = "descripcion 6",
                            Name = "nombre 6",
                            Price = 101m
                        },
                        new
                        {
                            ProductId = 7,
                            Description = "descripcion 7",
                            Name = "nombre 7",
                            Price = 49m
                        },
                        new
                        {
                            ProductId = 8,
                            Description = "descripcion 8",
                            Name = "nombre 8",
                            Price = 41m
                        },
                        new
                        {
                            ProductId = 9,
                            Description = "descripcion 9",
                            Name = "nombre 9",
                            Price = 127m
                        },
                        new
                        {
                            ProductId = 10,
                            Description = "descripcion 10",
                            Name = "nombre 10",
                            Price = 285m
                        },
                        new
                        {
                            ProductId = 11,
                            Description = "descripcion 11",
                            Name = "nombre 11",
                            Price = 200m
                        },
                        new
                        {
                            ProductId = 12,
                            Description = "descripcion 12",
                            Name = "nombre 12",
                            Price = 41m
                        },
                        new
                        {
                            ProductId = 13,
                            Description = "descripcion 13",
                            Name = "nombre 13",
                            Price = 194m
                        },
                        new
                        {
                            ProductId = 14,
                            Description = "descripcion 14",
                            Name = "nombre 14",
                            Price = 118m
                        },
                        new
                        {
                            ProductId = 15,
                            Description = "descripcion 15",
                            Name = "nombre 15",
                            Price = 218m
                        },
                        new
                        {
                            ProductId = 16,
                            Description = "descripcion 16",
                            Name = "nombre 16",
                            Price = 171m
                        },
                        new
                        {
                            ProductId = 17,
                            Description = "descripcion 17",
                            Name = "nombre 17",
                            Price = 1m
                        },
                        new
                        {
                            ProductId = 18,
                            Description = "descripcion 18",
                            Name = "nombre 18",
                            Price = 97m
                        },
                        new
                        {
                            ProductId = 19,
                            Description = "descripcion 19",
                            Name = "nombre 19",
                            Price = 210m
                        },
                        new
                        {
                            ProductId = 20,
                            Description = "descripcion 20",
                            Name = "nombre 20",
                            Price = 175m
                        },
                        new
                        {
                            ProductId = 21,
                            Description = "descripcion 21",
                            Name = "nombre 21",
                            Price = 269m
                        },
                        new
                        {
                            ProductId = 22,
                            Description = "descripcion 22",
                            Name = "nombre 22",
                            Price = 299m
                        },
                        new
                        {
                            ProductId = 23,
                            Description = "descripcion 23",
                            Name = "nombre 23",
                            Price = 200m
                        },
                        new
                        {
                            ProductId = 24,
                            Description = "descripcion 24",
                            Name = "nombre 24",
                            Price = 56m
                        },
                        new
                        {
                            ProductId = 25,
                            Description = "descripcion 25",
                            Name = "nombre 25",
                            Price = 269m
                        },
                        new
                        {
                            ProductId = 26,
                            Description = "descripcion 26",
                            Name = "nombre 26",
                            Price = 118m
                        },
                        new
                        {
                            ProductId = 27,
                            Description = "descripcion 27",
                            Name = "nombre 27",
                            Price = 164m
                        },
                        new
                        {
                            ProductId = 28,
                            Description = "descripcion 28",
                            Name = "nombre 28",
                            Price = 21m
                        },
                        new
                        {
                            ProductId = 29,
                            Description = "descripcion 29",
                            Name = "nombre 29",
                            Price = 33m
                        },
                        new
                        {
                            ProductId = 30,
                            Description = "descripcion 30",
                            Name = "nombre 30",
                            Price = 50m
                        },
                        new
                        {
                            ProductId = 31,
                            Description = "descripcion 31",
                            Name = "nombre 31",
                            Price = 102m
                        },
                        new
                        {
                            ProductId = 32,
                            Description = "descripcion 32",
                            Name = "nombre 32",
                            Price = 126m
                        },
                        new
                        {
                            ProductId = 33,
                            Description = "descripcion 33",
                            Name = "nombre 33",
                            Price = 2m
                        },
                        new
                        {
                            ProductId = 34,
                            Description = "descripcion 34",
                            Name = "nombre 34",
                            Price = 223m
                        },
                        new
                        {
                            ProductId = 35,
                            Description = "descripcion 35",
                            Name = "nombre 35",
                            Price = 104m
                        },
                        new
                        {
                            ProductId = 36,
                            Description = "descripcion 36",
                            Name = "nombre 36",
                            Price = 191m
                        },
                        new
                        {
                            ProductId = 37,
                            Description = "descripcion 37",
                            Name = "nombre 37",
                            Price = 119m
                        },
                        new
                        {
                            ProductId = 38,
                            Description = "descripcion 38",
                            Name = "nombre 38",
                            Price = 16m
                        },
                        new
                        {
                            ProductId = 39,
                            Description = "descripcion 39",
                            Name = "nombre 39",
                            Price = 16m
                        },
                        new
                        {
                            ProductId = 40,
                            Description = "descripcion 40",
                            Name = "nombre 40",
                            Price = 183m
                        },
                        new
                        {
                            ProductId = 41,
                            Description = "descripcion 41",
                            Name = "nombre 41",
                            Price = 29m
                        },
                        new
                        {
                            ProductId = 42,
                            Description = "descripcion 42",
                            Name = "nombre 42",
                            Price = 96m
                        },
                        new
                        {
                            ProductId = 43,
                            Description = "descripcion 43",
                            Name = "nombre 43",
                            Price = 171m
                        },
                        new
                        {
                            ProductId = 44,
                            Description = "descripcion 44",
                            Name = "nombre 44",
                            Price = 173m
                        },
                        new
                        {
                            ProductId = 45,
                            Description = "descripcion 45",
                            Name = "nombre 45",
                            Price = 287m
                        },
                        new
                        {
                            ProductId = 46,
                            Description = "descripcion 46",
                            Name = "nombre 46",
                            Price = 64m
                        },
                        new
                        {
                            ProductId = 47,
                            Description = "descripcion 47",
                            Name = "nombre 47",
                            Price = 94m
                        },
                        new
                        {
                            ProductId = 48,
                            Description = "descripcion 48",
                            Name = "nombre 48",
                            Price = 278m
                        },
                        new
                        {
                            ProductId = 49,
                            Description = "descripcion 49",
                            Name = "nombre 49",
                            Price = 17m
                        },
                        new
                        {
                            ProductId = 50,
                            Description = "descripcion 50",
                            Name = "nombre 50",
                            Price = 155m
                        },
                        new
                        {
                            ProductId = 51,
                            Description = "descripcion 51",
                            Name = "nombre 51",
                            Price = 283m
                        },
                        new
                        {
                            ProductId = 52,
                            Description = "descripcion 52",
                            Name = "nombre 52",
                            Price = 90m
                        },
                        new
                        {
                            ProductId = 53,
                            Description = "descripcion 53",
                            Name = "nombre 53",
                            Price = 133m
                        },
                        new
                        {
                            ProductId = 54,
                            Description = "descripcion 54",
                            Name = "nombre 54",
                            Price = 298m
                        },
                        new
                        {
                            ProductId = 55,
                            Description = "descripcion 55",
                            Name = "nombre 55",
                            Price = 120m
                        },
                        new
                        {
                            ProductId = 56,
                            Description = "descripcion 56",
                            Name = "nombre 56",
                            Price = 268m
                        },
                        new
                        {
                            ProductId = 57,
                            Description = "descripcion 57",
                            Name = "nombre 57",
                            Price = 88m
                        },
                        new
                        {
                            ProductId = 58,
                            Description = "descripcion 58",
                            Name = "nombre 58",
                            Price = 140m
                        },
                        new
                        {
                            ProductId = 59,
                            Description = "descripcion 59",
                            Name = "nombre 59",
                            Price = 254m
                        },
                        new
                        {
                            ProductId = 60,
                            Description = "descripcion 60",
                            Name = "nombre 60",
                            Price = 45m
                        },
                        new
                        {
                            ProductId = 61,
                            Description = "descripcion 61",
                            Name = "nombre 61",
                            Price = 18m
                        },
                        new
                        {
                            ProductId = 62,
                            Description = "descripcion 62",
                            Name = "nombre 62",
                            Price = 59m
                        },
                        new
                        {
                            ProductId = 63,
                            Description = "descripcion 63",
                            Name = "nombre 63",
                            Price = 257m
                        },
                        new
                        {
                            ProductId = 64,
                            Description = "descripcion 64",
                            Name = "nombre 64",
                            Price = 18m
                        },
                        new
                        {
                            ProductId = 65,
                            Description = "descripcion 65",
                            Name = "nombre 65",
                            Price = 43m
                        },
                        new
                        {
                            ProductId = 66,
                            Description = "descripcion 66",
                            Name = "nombre 66",
                            Price = 49m
                        },
                        new
                        {
                            ProductId = 67,
                            Description = "descripcion 67",
                            Name = "nombre 67",
                            Price = 60m
                        },
                        new
                        {
                            ProductId = 68,
                            Description = "descripcion 68",
                            Name = "nombre 68",
                            Price = 201m
                        },
                        new
                        {
                            ProductId = 69,
                            Description = "descripcion 69",
                            Name = "nombre 69",
                            Price = 296m
                        },
                        new
                        {
                            ProductId = 70,
                            Description = "descripcion 70",
                            Name = "nombre 70",
                            Price = 280m
                        },
                        new
                        {
                            ProductId = 71,
                            Description = "descripcion 71",
                            Name = "nombre 71",
                            Price = 42m
                        },
                        new
                        {
                            ProductId = 72,
                            Description = "descripcion 72",
                            Name = "nombre 72",
                            Price = 213m
                        },
                        new
                        {
                            ProductId = 73,
                            Description = "descripcion 73",
                            Name = "nombre 73",
                            Price = 66m
                        },
                        new
                        {
                            ProductId = 74,
                            Description = "descripcion 74",
                            Name = "nombre 74",
                            Price = 275m
                        },
                        new
                        {
                            ProductId = 75,
                            Description = "descripcion 75",
                            Name = "nombre 75",
                            Price = 226m
                        },
                        new
                        {
                            ProductId = 76,
                            Description = "descripcion 76",
                            Name = "nombre 76",
                            Price = 96m
                        },
                        new
                        {
                            ProductId = 77,
                            Description = "descripcion 77",
                            Name = "nombre 77",
                            Price = 275m
                        },
                        new
                        {
                            ProductId = 78,
                            Description = "descripcion 78",
                            Name = "nombre 78",
                            Price = 110m
                        },
                        new
                        {
                            ProductId = 79,
                            Description = "descripcion 79",
                            Name = "nombre 79",
                            Price = 66m
                        },
                        new
                        {
                            ProductId = 80,
                            Description = "descripcion 80",
                            Name = "nombre 80",
                            Price = 118m
                        },
                        new
                        {
                            ProductId = 81,
                            Description = "descripcion 81",
                            Name = "nombre 81",
                            Price = 206m
                        },
                        new
                        {
                            ProductId = 82,
                            Description = "descripcion 82",
                            Name = "nombre 82",
                            Price = 116m
                        },
                        new
                        {
                            ProductId = 83,
                            Description = "descripcion 83",
                            Name = "nombre 83",
                            Price = 236m
                        },
                        new
                        {
                            ProductId = 84,
                            Description = "descripcion 84",
                            Name = "nombre 84",
                            Price = 126m
                        },
                        new
                        {
                            ProductId = 85,
                            Description = "descripcion 85",
                            Name = "nombre 85",
                            Price = 166m
                        },
                        new
                        {
                            ProductId = 86,
                            Description = "descripcion 86",
                            Name = "nombre 86",
                            Price = 80m
                        },
                        new
                        {
                            ProductId = 87,
                            Description = "descripcion 87",
                            Name = "nombre 87",
                            Price = 158m
                        },
                        new
                        {
                            ProductId = 88,
                            Description = "descripcion 88",
                            Name = "nombre 88",
                            Price = 146m
                        },
                        new
                        {
                            ProductId = 89,
                            Description = "descripcion 89",
                            Name = "nombre 89",
                            Price = 227m
                        },
                        new
                        {
                            ProductId = 90,
                            Description = "descripcion 90",
                            Name = "nombre 90",
                            Price = 208m
                        },
                        new
                        {
                            ProductId = 91,
                            Description = "descripcion 91",
                            Name = "nombre 91",
                            Price = 112m
                        },
                        new
                        {
                            ProductId = 92,
                            Description = "descripcion 92",
                            Name = "nombre 92",
                            Price = 121m
                        },
                        new
                        {
                            ProductId = 93,
                            Description = "descripcion 93",
                            Name = "nombre 93",
                            Price = 203m
                        },
                        new
                        {
                            ProductId = 94,
                            Description = "descripcion 94",
                            Name = "nombre 94",
                            Price = 215m
                        },
                        new
                        {
                            ProductId = 95,
                            Description = "descripcion 95",
                            Name = "nombre 95",
                            Price = 239m
                        },
                        new
                        {
                            ProductId = 96,
                            Description = "descripcion 96",
                            Name = "nombre 96",
                            Price = 116m
                        },
                        new
                        {
                            ProductId = 97,
                            Description = "descripcion 97",
                            Name = "nombre 97",
                            Price = 106m
                        },
                        new
                        {
                            ProductId = 98,
                            Description = "descripcion 98",
                            Name = "nombre 98",
                            Price = 228m
                        },
                        new
                        {
                            ProductId = 99,
                            Description = "descripcion 99",
                            Name = "nombre 99",
                            Price = 134m
                        },
                        new
                        {
                            ProductId = 100,
                            Description = "descripcion 100",
                            Name = "nombre 100",
                            Price = 169m
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.Property<int>("ProductInStockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductInStockId"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductInStockId");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.HasIndex("ProductInStockId");

                    b.ToTable("Stocks", "Catalog");

                    b.HasData(
                        new
                        {
                            ProductInStockId = 1,
                            ProductId = 1,
                            Stock = 45
                        },
                        new
                        {
                            ProductInStockId = 2,
                            ProductId = 2,
                            Stock = 476
                        },
                        new
                        {
                            ProductInStockId = 3,
                            ProductId = 3,
                            Stock = 401
                        },
                        new
                        {
                            ProductInStockId = 4,
                            ProductId = 4,
                            Stock = 305
                        },
                        new
                        {
                            ProductInStockId = 5,
                            ProductId = 5,
                            Stock = 35
                        },
                        new
                        {
                            ProductInStockId = 6,
                            ProductId = 6,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 7,
                            ProductId = 7,
                            Stock = 215
                        },
                        new
                        {
                            ProductInStockId = 8,
                            ProductId = 8,
                            Stock = 471
                        },
                        new
                        {
                            ProductInStockId = 9,
                            ProductId = 9,
                            Stock = 113
                        },
                        new
                        {
                            ProductInStockId = 10,
                            ProductId = 10,
                            Stock = 159
                        },
                        new
                        {
                            ProductInStockId = 11,
                            ProductId = 11,
                            Stock = 50
                        },
                        new
                        {
                            ProductInStockId = 12,
                            ProductId = 12,
                            Stock = 93
                        },
                        new
                        {
                            ProductInStockId = 13,
                            ProductId = 13,
                            Stock = 26
                        },
                        new
                        {
                            ProductInStockId = 14,
                            ProductId = 14,
                            Stock = 205
                        },
                        new
                        {
                            ProductInStockId = 15,
                            ProductId = 15,
                            Stock = 220
                        },
                        new
                        {
                            ProductInStockId = 16,
                            ProductId = 16,
                            Stock = 114
                        },
                        new
                        {
                            ProductInStockId = 17,
                            ProductId = 17,
                            Stock = 308
                        },
                        new
                        {
                            ProductInStockId = 18,
                            ProductId = 18,
                            Stock = 142
                        },
                        new
                        {
                            ProductInStockId = 19,
                            ProductId = 19,
                            Stock = 75
                        },
                        new
                        {
                            ProductInStockId = 20,
                            ProductId = 20,
                            Stock = 22
                        },
                        new
                        {
                            ProductInStockId = 21,
                            ProductId = 21,
                            Stock = 151
                        },
                        new
                        {
                            ProductInStockId = 22,
                            ProductId = 22,
                            Stock = 100
                        },
                        new
                        {
                            ProductInStockId = 23,
                            ProductId = 23,
                            Stock = 349
                        },
                        new
                        {
                            ProductInStockId = 24,
                            ProductId = 24,
                            Stock = 73
                        },
                        new
                        {
                            ProductInStockId = 25,
                            ProductId = 25,
                            Stock = 460
                        },
                        new
                        {
                            ProductInStockId = 26,
                            ProductId = 26,
                            Stock = 310
                        },
                        new
                        {
                            ProductInStockId = 27,
                            ProductId = 27,
                            Stock = 245
                        },
                        new
                        {
                            ProductInStockId = 28,
                            ProductId = 28,
                            Stock = 145
                        },
                        new
                        {
                            ProductInStockId = 29,
                            ProductId = 29,
                            Stock = 452
                        },
                        new
                        {
                            ProductInStockId = 30,
                            ProductId = 30,
                            Stock = 187
                        },
                        new
                        {
                            ProductInStockId = 31,
                            ProductId = 31,
                            Stock = 390
                        },
                        new
                        {
                            ProductInStockId = 32,
                            ProductId = 32,
                            Stock = 379
                        },
                        new
                        {
                            ProductInStockId = 33,
                            ProductId = 33,
                            Stock = 384
                        },
                        new
                        {
                            ProductInStockId = 34,
                            ProductId = 34,
                            Stock = 69
                        },
                        new
                        {
                            ProductInStockId = 35,
                            ProductId = 35,
                            Stock = 55
                        },
                        new
                        {
                            ProductInStockId = 36,
                            ProductId = 36,
                            Stock = 144
                        },
                        new
                        {
                            ProductInStockId = 37,
                            ProductId = 37,
                            Stock = 347
                        },
                        new
                        {
                            ProductInStockId = 38,
                            ProductId = 38,
                            Stock = 196
                        },
                        new
                        {
                            ProductInStockId = 39,
                            ProductId = 39,
                            Stock = 71
                        },
                        new
                        {
                            ProductInStockId = 40,
                            ProductId = 40,
                            Stock = 400
                        },
                        new
                        {
                            ProductInStockId = 41,
                            ProductId = 41,
                            Stock = 351
                        },
                        new
                        {
                            ProductInStockId = 42,
                            ProductId = 42,
                            Stock = 352
                        },
                        new
                        {
                            ProductInStockId = 43,
                            ProductId = 43,
                            Stock = 460
                        },
                        new
                        {
                            ProductInStockId = 44,
                            ProductId = 44,
                            Stock = 454
                        },
                        new
                        {
                            ProductInStockId = 45,
                            ProductId = 45,
                            Stock = 297
                        },
                        new
                        {
                            ProductInStockId = 46,
                            ProductId = 46,
                            Stock = 193
                        },
                        new
                        {
                            ProductInStockId = 47,
                            ProductId = 47,
                            Stock = 121
                        },
                        new
                        {
                            ProductInStockId = 48,
                            ProductId = 48,
                            Stock = 162
                        },
                        new
                        {
                            ProductInStockId = 49,
                            ProductId = 49,
                            Stock = 243
                        },
                        new
                        {
                            ProductInStockId = 50,
                            ProductId = 50,
                            Stock = 93
                        },
                        new
                        {
                            ProductInStockId = 51,
                            ProductId = 51,
                            Stock = 230
                        },
                        new
                        {
                            ProductInStockId = 52,
                            ProductId = 52,
                            Stock = 21
                        },
                        new
                        {
                            ProductInStockId = 53,
                            ProductId = 53,
                            Stock = 142
                        },
                        new
                        {
                            ProductInStockId = 54,
                            ProductId = 54,
                            Stock = 473
                        },
                        new
                        {
                            ProductInStockId = 55,
                            ProductId = 55,
                            Stock = 273
                        },
                        new
                        {
                            ProductInStockId = 56,
                            ProductId = 56,
                            Stock = 494
                        },
                        new
                        {
                            ProductInStockId = 57,
                            ProductId = 57,
                            Stock = 111
                        },
                        new
                        {
                            ProductInStockId = 58,
                            ProductId = 58,
                            Stock = 353
                        },
                        new
                        {
                            ProductInStockId = 59,
                            ProductId = 59,
                            Stock = 497
                        },
                        new
                        {
                            ProductInStockId = 60,
                            ProductId = 60,
                            Stock = 225
                        },
                        new
                        {
                            ProductInStockId = 61,
                            ProductId = 61,
                            Stock = 42
                        },
                        new
                        {
                            ProductInStockId = 62,
                            ProductId = 62,
                            Stock = 489
                        },
                        new
                        {
                            ProductInStockId = 63,
                            ProductId = 63,
                            Stock = 498
                        },
                        new
                        {
                            ProductInStockId = 64,
                            ProductId = 64,
                            Stock = 391
                        },
                        new
                        {
                            ProductInStockId = 65,
                            ProductId = 65,
                            Stock = 147
                        },
                        new
                        {
                            ProductInStockId = 66,
                            ProductId = 66,
                            Stock = 129
                        },
                        new
                        {
                            ProductInStockId = 67,
                            ProductId = 67,
                            Stock = 495
                        },
                        new
                        {
                            ProductInStockId = 68,
                            ProductId = 68,
                            Stock = 91
                        },
                        new
                        {
                            ProductInStockId = 69,
                            ProductId = 69,
                            Stock = 72
                        },
                        new
                        {
                            ProductInStockId = 70,
                            ProductId = 70,
                            Stock = 243
                        },
                        new
                        {
                            ProductInStockId = 71,
                            ProductId = 71,
                            Stock = 414
                        },
                        new
                        {
                            ProductInStockId = 72,
                            ProductId = 72,
                            Stock = 358
                        },
                        new
                        {
                            ProductInStockId = 73,
                            ProductId = 73,
                            Stock = 231
                        },
                        new
                        {
                            ProductInStockId = 74,
                            ProductId = 74,
                            Stock = 131
                        },
                        new
                        {
                            ProductInStockId = 75,
                            ProductId = 75,
                            Stock = 278
                        },
                        new
                        {
                            ProductInStockId = 76,
                            ProductId = 76,
                            Stock = 123
                        },
                        new
                        {
                            ProductInStockId = 77,
                            ProductId = 77,
                            Stock = 198
                        },
                        new
                        {
                            ProductInStockId = 78,
                            ProductId = 78,
                            Stock = 132
                        },
                        new
                        {
                            ProductInStockId = 79,
                            ProductId = 79,
                            Stock = 116
                        },
                        new
                        {
                            ProductInStockId = 80,
                            ProductId = 80,
                            Stock = 66
                        },
                        new
                        {
                            ProductInStockId = 81,
                            ProductId = 81,
                            Stock = 273
                        },
                        new
                        {
                            ProductInStockId = 82,
                            ProductId = 82,
                            Stock = 266
                        },
                        new
                        {
                            ProductInStockId = 83,
                            ProductId = 83,
                            Stock = 474
                        },
                        new
                        {
                            ProductInStockId = 84,
                            ProductId = 84,
                            Stock = 234
                        },
                        new
                        {
                            ProductInStockId = 85,
                            ProductId = 85,
                            Stock = 469
                        },
                        new
                        {
                            ProductInStockId = 86,
                            ProductId = 86,
                            Stock = 193
                        },
                        new
                        {
                            ProductInStockId = 87,
                            ProductId = 87,
                            Stock = 85
                        },
                        new
                        {
                            ProductInStockId = 88,
                            ProductId = 88,
                            Stock = 222
                        },
                        new
                        {
                            ProductInStockId = 89,
                            ProductId = 89,
                            Stock = 430
                        },
                        new
                        {
                            ProductInStockId = 90,
                            ProductId = 90,
                            Stock = 342
                        },
                        new
                        {
                            ProductInStockId = 91,
                            ProductId = 91,
                            Stock = 125
                        },
                        new
                        {
                            ProductInStockId = 92,
                            ProductId = 92,
                            Stock = 120
                        },
                        new
                        {
                            ProductInStockId = 93,
                            ProductId = 93,
                            Stock = 278
                        },
                        new
                        {
                            ProductInStockId = 94,
                            ProductId = 94,
                            Stock = 181
                        },
                        new
                        {
                            ProductInStockId = 95,
                            ProductId = 95,
                            Stock = 465
                        },
                        new
                        {
                            ProductInStockId = 96,
                            ProductId = 96,
                            Stock = 13
                        },
                        new
                        {
                            ProductInStockId = 97,
                            ProductId = 97,
                            Stock = 48
                        },
                        new
                        {
                            ProductInStockId = 98,
                            ProductId = 98,
                            Stock = 68
                        },
                        new
                        {
                            ProductInStockId = 99,
                            ProductId = 99,
                            Stock = 155
                        },
                        new
                        {
                            ProductInStockId = 100,
                            ProductId = 100,
                            Stock = 146
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.HasOne("Catalog.Domain.Product", null)
                        .WithOne("Stock")
                        .HasForeignKey("Catalog.Domain.ProductInStock", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Navigation("Stock")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
